name: Deploy to GitHub Pages
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - name: Verify repository contents
        run: ls -R
      - name: Find package.json
        run: find . -name package.json || echo "No package.json found in any directory"
      - name: Check package.json in root
        run: test -f package.json && echo "package.json found in root" || echo "package.json missing in root"
      - name: Validate package.json
        run: test -f package.json && (cat package.json && jq . package.json || echo "package.json invalid") || echo "Skipping validation: package.json not found"
      - name: Create fallback package.json if missing
        run: |
          if [ ! -f package.json ]; then
            echo '{
              "name": "portfolio",
              "private": true,
              "version": "0.0.0",
              "homepage": "https://TanujairamV.github.io/portfolio",
              "type": "module",
              "scripts": {
                "dev": "vite",
                "build": "vite build",
                "lint": "eslint . --ext js,jsx --report-unused-disable-directives --max-warnings 0",
                "format": "prettier --write .",
                "preview": "vite preview",
                "deploy": "vite build && gh-pages -d dist"
              },
              "dependencies": {
                "aos": "^2.3.4",
                "emailjs-com": "^3.2.0",
                "framer-motion": "^10.16.4",
                "gsap": "^3.12.2",
                "react": "^18.2.0",
                "react-dom": "^18.2.0",
                "react-icons": "^4.10.1",
                "react-parallax-tilt": "^1.7.2",
                "react-scroll-parallax": "^3.4.2",
                "react-tsparticles": "^2.12.2",
                "tsparticles-slim": "^2.12.0"
              },
              "devDependencies": {
                "@types/react": "^18.2.15",
                "@types/react-dom": "^18.2.7",
                "@vitejs/plugin-react": "^4.0.3",
                "autoprefixer": "^10.4.14",
                "eslint": "^8.45.0",
                "eslint-config-prettier": "^9.0.0",
                "eslint-plugin-react": "^7.32.2",
                "eslint-plugin-react-hooks": "^4.6.0",
                "eslint-plugin-react-refresh": "^0.4.3",
                "gh-pages": "^5.0.0",
                "postcss": "^8.4.27",
                "prettier": "^3.0.0",
                "tailwindcss": "^3.3.3",
                "vite": "^4.4.5"
              }
            }' > package.json
            echo "Created fallback package.json"
          fi
      - name: Install dependencies and generate package-lock.json
        run: npm install --package-lock
      - name: Verify package-lock.json
        run: ls -l package-lock.json || echo "package-lock.json not generated"
      - name: Build
        run: npm run build
        env:
          VITE_BASE: /portfolio/
      - name: Copy index.html to 404.html
        run: cp dist/index.html dist/404.html
      - name: Verify dist contents
        run: ls -R dist/
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          force_orphan: true
