name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create fallback package.json if missing
        run: |
          if [ ! -f package.json ]; then
            echo '{
              "name": "portfolio",
              "private": true,
              "version": "0.0.0",
              "homepage": "https://TanujairamV.github.io/portfolio",
              "type": "module",
              "scripts": {
                "dev": "vite",
                "build": "vite build",
                "lint": "eslint . --ext js,jsx --report-unused-disable-directives --max-warnings 0",
                "format": "prettier --write .",
                "preview": "vite preview",
                "deploy": "vite build && gh-pages -d dist"
              },
              "dependencies": {
                "aos": "^2.3.4",
                "emailjs-com": "^3.2.0",
                "framer-motion": "^10.16.4",
                "gsap": "^3.12.2",
                "react": "^18.2.0",
                "react-dom": "^18.2.0",
                "react-icons": "^4.10.1",
                "react-parallax-tilt": "^1.7.2",
                "react-scroll-parallax": "^3.4.2",
                "react-tsparticles": "^2.12.2",
                "tsparticles-slim": "^2.12.0"
              },
              "devDependencies": {
                "@types/react": "^18.2.15",
                "@types/react-dom": "^18.2.7",
                "@vitejs/plugin-react": "^4.0.3",
                "autoprefixer": "^10.4.14",
                "eslint": "^8.45.0",
                "eslint-config-prettier": "^9.0.0",
                "eslint-plugin-react": "^7.32.2",
                "eslint-plugin-react-hooks": "^4.6.0",
                "eslint-plugin-react-refresh": "^0.4.3",
                "gh-pages": "^5.0.0",
                "postcss": "^8.4.27",
                "prettier": "^3.0.0",
                "tailwindcss": "^3.3.3",
                "vite": "^4.4.5"
              }
            }' > package.json
          fi

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          VITE_BASE: /portfolio/

      - name: Copy index.html to 404.html
        run: cp dist/index.html dist/404.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          force_orphan: true
