name: Deploy to GitHub Pages
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - name: Verify repository contents
        run: ls -R
      - name: Install dependencies and generate package-lock.json
        run: npm install --package-lock
      - name: Verify package-lock.json
        run: ls -l package-lock.json || echo "package-lock.json not found"
      - name: Build
        run: npm run build
        env:
          VITE_BASE: /portfolio/
      - name: Copy index.html to 404.html
        run: cp dist/index.html dist/404.html
      - name: Verify dist contents
        run: ls -R dist/
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          force_orphan: true
